[project]
name = "medimatch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "faiss-cpu",
    "langchain-community",
    "langchain-core",
    "langchain-groq",
    "langchain-huggingface",
    "langgraph",
    "pandas",
    "pydantic",
    "python-dotenv",
    "requests",
    "sentence-transformers",
    "streamlit",
    "torchvision>=0.28.0",
]
